export const LOGIN = 'AUTH/LOGIN'
export const LOGOUT = 'AUTH/LOGOUT'

export const GET_LOCATION_REQUEST = 'WEATHER/GET_LOCATION_REQUEST'
export const GET_LOCATION_SUCCESS = 'WEATHER/GET_LOCATION_SUCCESS'
export const GET_LOCATION_FAILED = 'WEATHER/GET_LOCATION_FAILED'
export const SET_CURRENT_LOCATION = 'WEATHER/SET'

export const GET_WEATHERS_REQUEST = 'WEATHER/GET_WEATHERS_REQUEST'
export const GET_WEATHERS_SUCCESS = 'WEATHER/GET_WEATHERS_SUCCESS'
export const GET_WEATHERS_FAILED = 'WEATHER/GET_WEATHERS_FAILED'
